#!/usr/bin/env node
// AUTO-GENERATED by scripts/bundle-cli.mjs — do not edit. Source: packages/accio-mcp/

import { createHash, randomBytes } from 'node:crypto';
import { createServer } from 'node:http';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { spawn } from 'node:child_process';

// ==== config.mjs ====
/**
 * 全局常量配置。
 * GEOLY_BASE_URL 环境变量仅用于本地联调（指向 staging 等），生产默认 app.geoly.ai。
 * 凭据文件路径 ~/.geoly/credentials 是与 Accio Work connector 声明
 * （connectors.json → cli.credential.home = ".geoly/credentials"）绑定的硬契约，不能改。
 */
const BASE_URL = process.env.GEOLY_BASE_URL || 'https://app.geoly.ai';
const MCP_URL = `${BASE_URL}/api/mcp`;
const CRED_DIR = join(homedir(), '.geoly');
const CRED_FILE = join(CRED_DIR, 'credentials');
const CLIENT_NAME = 'geoly-accio-plugin';
const VERSION = "0.2.4";
const OAUTH_SCOPE = 'openid profile email offline_access';

// 登录守护进程(login helper)的握手文件：helper 上报回调端口 / login 下发一次性 OAuth 配置 /
// helper 回报失败原因。均为瞬态文件，成功或超时后清理。
const LOGIN_HELPER_FILE = join(CRED_DIR, 'login-helper.json');
const LOGIN_CONFIG_FILE = join(CRED_DIR, 'login-config.json');
const LOGIN_ERROR_FILE = join(CRED_DIR, 'login-error.json');

// ==== credentials.mjs ====
/**
 * 读取本地凭据文件（~/.geoly/credentials）。
 * 文件不存在或解析失败一律返回 null，由调用方决定引导登录还是报错。
 */
function loadCredentials() {
  try {
    return JSON.parse(readFileSync(CRED_FILE, 'utf8'));
  } catch {
    return null;
  }
}

/**
 * 写入凭据文件。
 * Accio Work 的硬契约：顶层必须有明文 account / email 字段（框架用它渲染授权卡片的账号标签，
 * 只认顶层明文，不解嵌套、不解密），后续版本升级不得把这两个字段挪走或改名。
 */
function saveCredentials(creds) {
  mkdirSync(CRED_DIR, { recursive: true });
  writeFileSync(CRED_FILE, `${JSON.stringify(creds, null, 2)}\n`, { mode: 0o600 });
}

/** 删除凭据文件（logout 用），连带清理登录守护进程的瞬态握手文件。 */
function clearCredentials() {
  for (const f of [LOGIN_HELPER_FILE, LOGIN_CONFIG_FILE, LOGIN_ERROR_FILE]) {
    try {
      rmSync(f);
    } catch {
      /* 无残留 */
    }
  }
  try {
    rmSync(CRED_FILE);
    return true;
  } catch {
    return false;
  }
}

// ==== oauth.mjs ====
const LOGIN_TIMEOUT_MS = 10 * 60 * 1000;

/** base64url 编码（Node 18 Buffer 原生支持）。 */
function b64url(buf) {
  return Buffer.from(buf).toString('base64url');
}

/** 简单 sleep。 */
function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

/**
 * 拉取授权服务器元数据（RFC 8414）。
 * GEOly 生产返回 authorization/token/userinfo/registration 四个端点，均已实测存在。
 */
async function discoverAuthServer() {
  const res = await fetch(`${BASE_URL}/.well-known/oauth-authorization-server`, {
    headers: { Accept: 'application/json' },
  });
  if (!res.ok) throw new Error(`OAuth discovery failed: HTTP ${res.status}`);
  const meta = await res.json();
  for (const k of ['authorization_endpoint', 'token_endpoint', 'registration_endpoint']) {
    if (!meta[k]) throw new Error(`OAuth discovery missing ${k}`);
  }
  return meta;
}

/**
 * 动态客户端注册（RFC 7591）。
 * GEOly 支持 token_endpoint_auth_method=none 的公共客户端；redirect_uri 为本机 loopback 回调，
 * 每次登录端口随机，因此每次登录注册一个新 client（服务端幂等治理）。
 */
async function registerClient(meta, redirectUri) {
  const res = await fetch(meta.registration_endpoint, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
    body: JSON.stringify({
      client_name: 'GEOly Accio Plugin',
      redirect_uris: [redirectUri],
      grant_types: ['authorization_code', 'refresh_token'],
      response_types: ['code'],
      token_endpoint_auth_method: 'none',
      scope: OAUTH_SCOPE,
    }),
  });
  if (!res.ok) {
    throw new Error(`Dynamic client registration failed: HTTP ${res.status} ${await res.text()}`);
  }
  return res.json();
}

/**
 * 跨平台打开浏览器。用绝对路径调系统 opener——被 Accio 这类 GUI App 以受限 PATH 的
 * 子进程拉起时，相对命令名可能解析不到。
 * ⚠️ Windows 不能裸走 `cmd /c start <url>`：URL 里的 & 是 cmd 元字符，会把 URL 在
 * 第一个 & 处截断（authorize 链接丢 client_id → invalid_client，实测复现）。
 * 首选 rundll32（不经 shell 解析，URL 原样传），cmd start 兜底时必须 ^ 转义 &。
 * GEOLY_NO_BROWSER=1 时跳过（测试/无头环境）。失败不抛错：授权 URL 已显著打印。
 */
function openBrowser(url) {
  if (process.env.GEOLY_NO_BROWSER) return false;
  const candidates =
    process.platform === 'win32'
      ? [
          ['rundll32', ['url.dll,FileProtocolHandler', url]],
          ['cmd', ['/c', 'start', '', url.replace(/&/g, '^&')]],
        ]
      : process.platform === 'darwin'
        ? [['/usr/bin/open', [url]], ['open', [url]]]
        : [['/usr/bin/xdg-open', [url]], ['xdg-open', [url]]];
  for (const [cmd, args] of candidates) {
    try {
      const child = spawn(cmd, args, { stdio: 'ignore', detached: true });
      child.on('error', () => {});
      child.unref();
      return true;
    } catch {
      /* 试下一个候选 */
    }
  }
  return false;
}

/** 解 JWT payload（不验签——仅取展示用的 email/name；数据面鉴权在服务端）。 */
function decodeJwtPayload(jwt) {
  try {
    return JSON.parse(Buffer.from(jwt.split('.')[1], 'base64url').toString('utf8'));
  } catch {
    return null;
  }
}

/**
 * 授权码换 token（PKCE 公共客户端，带 RFC 8707 resource 参数指向 MCP 端点）。
 * refresh 时复用同一函数，grant 参数不同。
 */
async function tokenRequest(tokenEndpoint, params) {
  const res = await fetch(tokenEndpoint, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', Accept: 'application/json' },
    body: new URLSearchParams({ ...params, resource: MCP_URL }).toString(),
  });
  const body = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new Error(
      `Token request failed: HTTP ${res.status} ${body.error || ''} ${body.error_description || ''}`.trim()
    );
  }
  return body;
}

/**
 * 幂等预检：本地凭据仍有效（或可用 refresh_token 换新）就直接成功返回，不再走浏览器。
 * 价值：宿主(Accio)对登录进程可能有超时会中途处决——守护进程最终会把凭据落盘，
 * 用户重试时这里秒过，不用重新授权。
 */
async function tryExistingCredentials() {
  const creds = loadCredentials();
  if (!creds?.access_token) return false;
  if (creds.expires_at && creds.expires_at - Date.now() > 60_000) {
    console.error(`[geoly] Already signed in as ${creds.account}.`);
    return true;
  }
  if (creds.refresh_token && creds.token_endpoint) {
    try {
      const next = await refreshCredentials(creds);
      console.error(`[geoly] Session refreshed for ${next.account}.`);
      return true;
    } catch {
      /* 刷新失败 → 走完整浏览器流 */
    }
  }
  return false;
}

/** 读失败上报文件（helper 写）；解析失败返回 null。 */
function readLoginError() {
  try {
    return JSON.parse(readFileSync(LOGIN_ERROR_FILE, 'utf8'));
  } catch {
    return null;
  }
}

/** 轮询等待文件出现并通过 pick 提取字段；超时抛错。 */
async function waitForFile(file, timeoutMs, pick) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const v = pick(JSON.parse(readFileSync(file, 'utf8')));
      if (v !== undefined && v !== null) return v;
    } catch {
      /* 尚未写入 */
    }
    await sleep(100);
  }
  throw new Error(`Timed out waiting for ${file}`);
}

/**
 * 登录主流程（编排进程）。核心设计：回调服务 + 授权码交换 + 凭据落盘全部放进
 * **双重派生的独立守护进程**（login → spawner(即退) → helper(常驻)）——宿主(Accio)
 * 对登录进程有超时处决时，杀掉本进程（甚至整棵进程树）也不影响授权完成；凭据最终
 * 落盘后宿主按「凭据文件出现」判定连接成功，或用户重试时幂等预检秒过。
 *
 * 流程：幂等预检 → 发现端点 → 起守护进程(文件握手拿回调端口) → DCR 注册 →
 * 下发一次性 OAuth 配置(0600) → 弹浏览器 → 轮询等待凭据出现/失败上报。
 */
async function login() {
  if (await tryExistingCredentials()) return;

  const meta = await discoverAuthServer();

  mkdirSync(CRED_DIR, { recursive: true });
  for (const f of [LOGIN_HELPER_FILE, LOGIN_CONFIG_FILE, LOGIN_ERROR_FILE]) {
    try {
      rmSync(f);
    } catch {
      /* 无残留 */
    }
  }

  const startedAt = Date.now();

  // 双重派生断开进程树：中间层立刻退出，helper 不再是本进程的子孙
  spawn(process.execPath, [process.argv[1], '__login_spawn__'], {
    detached: true,
    stdio: 'ignore',
    windowsHide: true,
  }).unref();

  const port = await waitForFile(LOGIN_HELPER_FILE, 10_000, (j) => j.port);
  const redirectUri = `http://127.0.0.1:${port}/callback`;

  const client = await registerClient(meta, redirectUri);

  const verifier = b64url(randomBytes(32));
  const challenge = b64url(createHash('sha256').update(verifier).digest());
  const state = b64url(randomBytes(16));

  // 一次性配置下发给 helper（读取后即删；0600 与凭据文件同信任边界）
  writeFileSync(
    LOGIN_CONFIG_FILE,
    JSON.stringify({
      state,
      verifier,
      client_id: client.client_id,
      client_secret: client.client_secret || null,
      token_endpoint: meta.token_endpoint,
      userinfo_endpoint: meta.userinfo_endpoint || null,
      redirect_uri: redirectUri,
      started_at: startedAt,
    }),
    { mode: 0o600 }
  );

  const authUrl = new URL(meta.authorization_endpoint);
  authUrl.search = new URLSearchParams({
    response_type: 'code',
    client_id: client.client_id,
    redirect_uri: redirectUri,
    scope: OAUTH_SCOPE,
    state,
    code_challenge: challenge,
    code_challenge_method: 'S256',
    resource: MCP_URL,
  }).toString();

  // 显著打印授权 URL 到 stdout 和 stderr：即便自动弹窗被 GUI 宿主拦掉，
  // Accio 日志或用户终端里也能拿到链接手动打开。
  const banner = `\n========================================\nSign in to GEOly — open this URL in your browser:\n${authUrl}\n========================================\n`;
  process.stdout.write(banner);
  console.error(banner);
  const opened = openBrowser(authUrl.toString());
  console.error(
    opened
      ? '[geoly] Opened your default browser. Complete sign-in there.'
      : '[geoly] Browser not auto-opened — please open the URL above manually.'
  );

  // 等 helper 把凭据落盘（本进程被处决也没关系——helper 独立完成，重试幂等秒过）
  const deadline = startedAt + LOGIN_TIMEOUT_MS;
  while (Date.now() < deadline) {
    const creds = loadCredentials();
    if (creds?.obtained_at && creds.obtained_at >= startedAt) {
      console.error(`[geoly] Signed in as ${creds.account}. You can close the browser tab.`);
      return;
    }
    const err = readLoginError();
    if (err?.at && err.at >= startedAt) {
      try {
        rmSync(LOGIN_ERROR_FILE);
      } catch {}
      throw new Error(err.message || 'Sign-in failed');
    }
    await sleep(500);
  }
  throw new Error('Sign-in timed out after 10 minutes');
}

/** 双重派生的中间层：起真正的 helper 后立刻退出，切断与 login 进程的树关系。 */
function runLoginSpawner() {
  spawn(process.execPath, [process.argv[1], '__login_helper__'], {
    detached: true,
    stdio: 'ignore',
    windowsHide: true,
  }).unref();
}

/** helper 侧失败上报 + 退出。 */
function helperFail(message, exitCode = 1) {
  try {
    mkdirSync(CRED_DIR, { recursive: true });
    writeFileSync(LOGIN_ERROR_FILE, JSON.stringify({ message, at: Date.now() }));
  } catch {}
  try {
    rmSync(LOGIN_HELPER_FILE);
  } catch {}
  process.exit(exitCode);
}

/**
 * 登录守护进程（独立存活，不受 login 进程死活影响）：
 * 绑定 loopback 回调端口 → 写握手文件上报端口 → 轮询读取一次性 OAuth 配置(读后即删) →
 * 接浏览器回调(校验 state) → 授权码换 token(PKCE) → 取身份(id_token/userinfo) →
 * 写 ~/.geoly/credentials(顶层明文 account/email = Accio 硬契约) → 回浏览器成功页 → 退出。
 * 总超时 10 分钟；任何失败写 LOGIN_ERROR_FILE 供编排进程/下次登录读取。
 */
async function runLoginHelper() {
  let cfg = null;
  let cfgResolve;
  const cfgReady = new Promise((r) => {
    cfgResolve = r;
  });
  const cfgTimer = setInterval(() => {
    try {
      cfg = JSON.parse(readFileSync(LOGIN_CONFIG_FILE, 'utf8'));
      try {
        rmSync(LOGIN_CONFIG_FILE);
      } catch {}
      clearInterval(cfgTimer);
      cfgResolve();
    } catch {
      /* 配置尚未写入 */
    }
  }, 100);

  // 配置迟迟不来（login 编排进程半路死了且没下发配置）→ 自杀清场
  setTimeout(() => {
    if (!cfg) helperFail('Login orchestrator never delivered OAuth config');
  }, 60_000);

  // 总超时：用户一直没完成浏览器授权
  setTimeout(() => helperFail('Sign-in timed out after 10 minutes'), LOGIN_TIMEOUT_MS);

  const finishPage = (res, ok, detail) => {
    res.writeHead(ok ? 200 : 400, { 'Content-Type': 'text/html; charset=utf-8' });
    res.end(
      `<!doctype html><meta charset="utf-8"><title>GEOly</title><body style="font-family:system-ui;display:grid;place-items:center;height:90vh"><div style="text-align:center"><h2>${ok ? 'Signed in to GEOly' : 'Sign-in failed'}</h2><p>${ok ? 'You can close this tab and return to Accio Work.' : detail}</p></div>`
    );
  };

  const server = createServer(async (req, res) => {
    const url = new URL(req.url, 'http://127.0.0.1');
    if (url.pathname !== '/callback') {
      res.writeHead(404).end();
      return;
    }
    await cfgReady; // 正常时序里配置远早于回调到达；此处仅兜底
    const err = url.searchParams.get('error');
    const code = url.searchParams.get('code');
    const state = url.searchParams.get('state');
    const fail = err
      ? `Authorization failed: ${err} ${url.searchParams.get('error_description') || ''}`
      : state !== cfg.state
        ? 'Authorization failed: state mismatch'
        : !code
          ? 'Authorization failed: missing code'
          : null;
    if (fail) {
      finishPage(res, false, fail);
      setTimeout(() => helperFail(fail), 300);
      return;
    }

    try {
      const params = {
        grant_type: 'authorization_code',
        code,
        redirect_uri: cfg.redirect_uri,
        client_id: cfg.client_id,
        code_verifier: cfg.verifier,
      };
      if (cfg.client_secret) params.client_secret = cfg.client_secret;
      const tokens = await tokenRequest(cfg.token_endpoint, params);

      // 身份信息：id_token 里拿 email/name；拿不到再打 userinfo；最后回退固定标签
      let identity = tokens.id_token ? decodeJwtPayload(tokens.id_token) : null;
      if (!identity?.email && cfg.userinfo_endpoint) {
        identity = await fetch(cfg.userinfo_endpoint, {
          headers: { Authorization: `Bearer ${tokens.access_token}` },
        })
          .then((r) => (r.ok ? r.json() : null))
          .catch(() => null);
      }
      const email = identity?.email || null;
      const account = email || identity?.name || 'GEOly account';

      saveCredentials({
        account,
        email,
        name: identity?.name || null,
        access_token: tokens.access_token,
        refresh_token: tokens.refresh_token || null,
        token_type: tokens.token_type || 'Bearer',
        expires_at: tokens.expires_in ? Date.now() + tokens.expires_in * 1000 : null,
        obtained_at: Date.now(),
        client_id: cfg.client_id,
        client_secret: cfg.client_secret || null,
        token_endpoint: cfg.token_endpoint,
        base_url: BASE_URL,
        client: `${CLIENT_NAME}/${VERSION}`,
      });

      finishPage(res, true);
      try {
        rmSync(LOGIN_HELPER_FILE);
      } catch {}
      setTimeout(() => process.exit(0), 300);
    } catch (e) {
      finishPage(res, false, e.message);
      setTimeout(() => helperFail(e.message), 300);
    }
  });

  await new Promise((resolve, reject) => {
    server.on('error', reject);
    server.listen(0, '127.0.0.1', resolve);
  });
  mkdirSync(CRED_DIR, { recursive: true });
  writeFileSync(
    LOGIN_HELPER_FILE,
    JSON.stringify({ port: server.address().port, pid: process.pid, at: Date.now() })
  );
}

/**
 * 用 refresh_token 刷新 access_token；服务端未轮换 refresh_token 时保留旧值。
 * 返回更新后的凭据对象（已落盘）。
 */
async function refreshCredentials(creds) {
  if (!creds?.refresh_token) throw new Error('no refresh_token');
  const params = {
    grant_type: 'refresh_token',
    refresh_token: creds.refresh_token,
    client_id: creds.client_id,
  };
  if (creds.client_secret) params.client_secret = creds.client_secret;
  const tokens = await tokenRequest(creds.token_endpoint, params);

  const next = {
    ...creds,
    access_token: tokens.access_token,
    refresh_token: tokens.refresh_token || creds.refresh_token,
    expires_at: tokens.expires_in ? Date.now() + tokens.expires_in * 1000 : creds.expires_at,
    obtained_at: Date.now(),
  };
  saveCredentials(next);
  return next;
}

// ==== bridge.mjs ====
const DEBUG = !!process.env.GEOLY_DEBUG;
const log = (...a) => DEBUG && console.error('[geoly-bridge]', ...a);

/** stdout 写一条 JSON-RPC 消息（newline-delimited，stdio MCP 传输格式）。 */
function writeMessage(msg) {
  process.stdout.write(`${JSON.stringify(msg)}\n`);
}

/** 给带 id 的请求回一条 JSON-RPC error（通知无 id 则静默丢弃）。 */
function writeError(id, code, message) {
  if (id === undefined || id === null) return;
  writeMessage({ jsonrpc: '2.0', id, error: { code, message } });
}

/**
 * token 管理器：GEOLY_API_KEY 环境变量（geom_ 静态只读 token）优先；
 * 否则用 ~/.geoly/credentials 的 OAuth token，过期前 60s 或收到 401 时用 refresh_token 换新。
 * refresh 单飞（并发请求共享同一次刷新）。
 */
function createTokenManager() {
  const staticKey = process.env.GEOLY_API_KEY || null;
  let creds = staticKey ? null : loadCredentials();
  let refreshing = null;

  const doRefresh = () => {
    refreshing ??= refreshCredentials(creds)
      .then((next) => {
        creds = next;
        return next;
      })
      .finally(() => {
        refreshing = null;
      });
    return refreshing;
  };

  return {
    /** 是否走 GEOLY_API_KEY 静态轨（影响 401 提示文案）。 */
    isStatic: !!staticKey,
    /** 取当前可用 token；无凭据返回 null。 */
    async get() {
      if (staticKey) return staticKey;
      if (!creds) {
        creds = loadCredentials();
        if (!creds) return null;
      }
      if (creds.expires_at && creds.expires_at - Date.now() < 60_000 && creds.refresh_token) {
        try {
          await doRefresh();
        } catch (e) {
          log('proactive refresh failed:', e.message);
        }
      }
      return creds.access_token || null;
    },
    /** 收到 401 后强制刷新一次；成功返回新 token，失败返回 null。 */
    async forceRefresh() {
      if (staticKey || !creds?.refresh_token) return null;
      try {
        await doRefresh();
        return creds.access_token || null;
      } catch (e) {
        log('refresh after 401 failed:', e.message);
        return null;
      }
    },
  };
}

/**
 * 解析 SSE 响应体（服务端对 POST 可能回 text/event-stream），
 * 把每个 event 的 data 行拼起来 JSON.parse 后逐条写回 stdout。
 */
async function pumpSseBody(res) {
  const decoder = new TextDecoder();
  let buf = '';
  const flushEvent = (raw) => {
    const data = raw
      .split('\n')
      .filter((l) => l.startsWith('data:'))
      .map((l) => l.slice(5).trimStart())
      .join('\n');
    if (!data) return;
    try {
      writeMessage(JSON.parse(data));
    } catch {
      log('unparseable SSE data:', data.slice(0, 200));
    }
  };
  for await (const chunk of res.body) {
    buf += decoder.decode(chunk, { stream: true });
    let idx;
    while ((idx = buf.indexOf('\n\n')) !== -1) {
      flushEvent(buf.slice(0, idx));
      buf = buf.slice(idx + 2);
    }
  }
  if (buf.trim()) flushEvent(buf);
}

/**
 * stdio ↔ Streamable HTTP 桥主循环。
 * GEOly 的远程 MCP 是无状态 Streamable HTTP（仅 POST；GET/DELETE 返 405、无服务端推送），
 * 因此桥是纯请求-响应转发：stdin 每行一条 JSON-RPC → POST 远端 → 响应(JSON 或 SSE)写回 stdout。
 */
async function runBridge() {
  const tokens = createTokenManager();
  let protocolVersion = null; // initialize 结果里记下，后续请求带 MCP-Protocol-Version 头

  const post = async (msg, token) => {
    const headers = {
      'Content-Type': 'application/json',
      Accept: 'application/json, text/event-stream',
      Authorization: `Bearer ${token}`,
      'X-Client-Name': CLIENT_NAME,
      'X-Client-Version': VERSION,
    };
    if (protocolVersion) headers['MCP-Protocol-Version'] = protocolVersion;
    return fetch(MCP_URL, { method: 'POST', headers, body: JSON.stringify(msg) });
  };

  const handle = async (msg) => {
    const id = msg?.id;
    let token = await tokens.get();
    if (!token) {
      writeError(
        id,
        -32002,
        'Not signed in to GEOly. Connect the GEOly connector (App Authorization → Connect), or run: geoly-accio-mcp login'
      );
      return;
    }

    try {
      let res = await post(msg, token);

      // 401 → 强制 refresh 一次再重试；仍失败则提示重新授权
      if (res.status === 401) {
        token = await tokens.forceRefresh();
        if (token) res = await post(msg, token);
        if (!token || res.status === 401) {
          writeError(
            id,
            -32001,
            tokens.isStatic
              ? 'GEOLY_API_KEY was rejected (invalid or revoked geom_ token). Issue a new token in the GEOly dashboard.'
              : 'GEOly session expired. Reconnect the GEOly connector (App Authorization → Connect), or run: geoly-accio-mcp login'
          );
          return;
        }
      }

      if (res.status === 202 || res.status === 204) return; // 通知已受理，无响应体

      const ctype = res.headers.get('content-type') || '';
      if (!res.ok) {
        const text = await res.text().catch(() => '');
        writeError(id, -32000, `GEOly MCP HTTP ${res.status}: ${text.slice(0, 400)}`);
        return;
      }

      if (ctype.includes('text/event-stream')) {
        await pumpSseBody(res);
        return;
      }

      const body = await res.json();
      for (const m of Array.isArray(body) ? body : [body]) {
        // 记录协商出的协议版本，供后续请求头使用
        if (m?.result?.protocolVersion) protocolVersion = m.result.protocolVersion;
        writeMessage(m);
      }
    } catch (e) {
      writeError(id, -32001, `GEOly MCP transport error: ${e.message}`);
    }
  };

  // stdin 逐行读取（newline-delimited JSON-RPC）。
  // 在途请求计数：stdin 关闭时必须等全部响应写完再退出，否则管道式客户端会丢响应。
  let pending = 0;
  let stdinEnded = false;
  const maybeExit = () => {
    if (stdinEnded && pending === 0) process.exit(0);
  };
  const track = (msg) => {
    pending++;
    void handle(msg).finally(() => {
      pending--;
      maybeExit();
    });
  };

  let buf = '';
  process.stdin.setEncoding('utf8');
  process.stdin.on('data', (chunk) => {
    buf += chunk;
    let idx;
    while ((idx = buf.indexOf('\n')) !== -1) {
      const line = buf.slice(0, idx).trim();
      buf = buf.slice(idx + 1);
      if (!line) continue;
      let msg;
      try {
        msg = JSON.parse(line);
      } catch {
        log('unparseable stdin line:', line.slice(0, 200));
        continue;
      }
      track(msg);
    }
  });
  process.stdin.on('end', () => {
    stdinEnded = true;
    maybeExit();
  });

  log(`bridge started → ${MCP_URL}`);
  // 保持进程存活直到 stdin 关闭
  await new Promise(() => {});
}

// ==== invoke.mjs ====
// call/tools 子命令的默认客户端超时（服务端重型工具上限 ~45s，留足余量）
const INVOKE_TIMEOUT_MS = 120_000;

/**
 * 把 SSE 响应体一次性收集为 JSON-RPC 消息数组。
 * 与桥的 pumpSseBody（流式写回 stdout）相对，这里用于一次性调用后统一取结果。
 */
async function readSseMessages(res) {
  const decoder = new TextDecoder();
  const messages = [];
  let buf = '';
  const flushEvent = (raw) => {
    const data = raw
      .split('\n')
      .filter((l) => l.startsWith('data:'))
      .map((l) => l.slice(5).trimStart())
      .join('\n');
    if (!data) return;
    try {
      messages.push(JSON.parse(data));
    } catch {
      // 非 JSON 的 SSE 数据行（心跳等）忽略
    }
  };
  for await (const chunk of res.body) {
    buf += decoder.decode(chunk, { stream: true });
    let idx;
    while ((idx = buf.indexOf('\n\n')) !== -1) {
      flushEvent(buf.slice(0, idx));
      buf = buf.slice(idx + 2);
    }
  }
  if (buf.trim()) flushEvent(buf);
  return messages;
}

/**
 * 一次性 JSON-RPC 调用：POST 远端（无状态 Streamable HTTP），
 * 复用桥的 token 管理（GEOLY_API_KEY 优先 / OAuth 过期刷新 / 401 强刷重试一次），
 * 兼容 JSON 与 SSE 两种响应格式，返回匹配请求 id 的 result；error 则抛出。
 */
async function rpcOnce(method, params, timeoutMs = INVOKE_TIMEOUT_MS) {
  const tokens = createTokenManager();
  let token = await tokens.get();
  if (!token) {
    throw new Error(
      'Not signed in to GEOly. Connect the GEOly connector (App Authorization → Connect), or run: geoly-accio-mcp login'
    );
  }

  const req = { jsonrpc: '2.0', id: 1, method, params };
  const ctl = new AbortController();
  const timer = setTimeout(() => ctl.abort(), timeoutMs);
  const post = (tok) =>
    fetch(MCP_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json, text/event-stream',
        Authorization: `Bearer ${tok}`,
        'X-Client-Name': CLIENT_NAME,
        'X-Client-Version': VERSION,
      },
      body: JSON.stringify(req),
      signal: ctl.signal,
    });

  try {
    let res = await post(token);
    if (res.status === 401) {
      token = await tokens.forceRefresh();
      if (token) res = await post(token);
      if (!token || res.status === 401) {
        throw new Error(
          tokens.isStatic
            ? 'GEOLY_API_KEY was rejected (invalid or revoked geom_ token). Issue a new token in the GEOly dashboard.'
            : 'GEOly session expired. Reconnect the GEOly connector (App Authorization → Connect), or run: geoly-accio-mcp login'
        );
      }
    }
    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new Error(`GEOly MCP HTTP ${res.status}: ${text.slice(0, 400)}`);
    }
    const ctype = res.headers.get('content-type') || '';
    const body = ctype.includes('text/event-stream') ? await readSseMessages(res) : await res.json();
    const msgs = Array.isArray(body) ? body : [body];
    const m = msgs.find((x) => x?.id === req.id) ?? msgs[msgs.length - 1];
    if (m?.error) throw new Error(m.error.message || JSON.stringify(m.error));
    return m?.result;
  } catch (e) {
    if (e.name === 'AbortError') {
      throw new Error(
        `Timed out after ${Math.round(timeoutMs / 1000)}s. Heavy tools can be slow on first call — retry once (server cache warms up), or narrow the query (shorter date range / platform filter), or raise --timeout.`
      );
    }
    throw e;
  } finally {
    clearTimeout(timer);
  }
}

/**
 * `geoly-accio-mcp tools`：列出当前账号可用的全部 GEOly 工具。
 * 默认每行一个（名称 + 描述首行），--json 输出完整 schema 供查参数。
 */
async function runTools({ json = false, timeoutMs } = {}) {
  const result = await rpcOnce('tools/list', {}, timeoutMs);
  const tools = result?.tools || [];
  if (json) {
    console.log(JSON.stringify(tools, null, 2));
    return;
  }
  console.log(
    `${tools.length} GEOly tools available. Invoke: geoly-accio-mcp call <tool> --json '<args JSON>'  (--json '{}' if no args; add --schema via: geoly-accio-mcp tools --json)\n`
  );
  for (const t of tools) {
    const desc = (t.description || '').split('\n')[0];
    console.log(`${t.name}\t${desc.length > 110 ? `${desc.slice(0, 110)}…` : desc}`);
  }
}

/**
 * `geoly-accio-mcp call <tool> --json '<args>'`：一次性调用某个 GEOly 工具并打印结果。
 * 参数只收一个整体 JSON 对象（杜绝 flag 式传参的类型强转坑）；
 * 工具业务失败（isError）打到 stderr 并以退出码 1 结束。
 */
async function runCall(name, argsJson, { timeoutMs } = {}) {
  let args = {};
  if (argsJson !== undefined) {
    try {
      args = JSON.parse(argsJson);
    } catch (e) {
      const err = new Error(`--json must be one valid JSON object, e.g. --json '{"time_range":"30d"}' (${e.message})`);
      err.exitCode = 2;
      throw err;
    }
  }
  const result = await rpcOnce('tools/call', { name, arguments: args }, timeoutMs);
  const texts = (result?.content || []).filter((c) => c?.type === 'text').map((c) => c.text);
  const out =
    texts.join('\n') ||
    (result?.structuredContent ? JSON.stringify(result.structuredContent, null, 2) : JSON.stringify(result ?? null));
  if (result?.isError) {
    console.error(out);
    process.exit(1);
  }
  console.log(out);
}

// ==== main.mjs ====
const HELP = `GEOly Accio connector CLI v${VERSION}

Usage:
  geoly-accio-mcp tools                          List available GEOly tools (--json = full parameter schemas)
  geoly-accio-mcp call <tool> --json '<args>'    Call one GEOly tool; args = ONE JSON object (--json '{}' if none)
                                                 Options: --timeout <seconds> (default 120)
  geoly-accio-mcp login                          Sign in to GEOly in your browser (writes ~/.geoly/credentials)
  geoly-accio-mcp logout                         Remove the stored GEOly session
  geoly-accio-mcp status                         Show sign-in status
  geoly-accio-mcp                                (no args) Run the stdio MCP bridge to ${MCP_URL}

Examples:
  geoly-accio-mcp call get_brand_overview --json '{"time_range":"30d"}'
  geoly-accio-mcp call search_public_entities --json '{"query":"wireless earbuds"}'

Exit codes: 0 ok · 1 tool/transport error · 2 usage error

Environment:
  GEOLY_API_KEY   Use a read-only geom_ static token instead of the stored login
  GEOLY_BASE_URL  Override the GEOly base URL (testing only)
  GEOLY_DEBUG     Verbose bridge logging on stderr
`;

/** 解析 tools/call 子命令的选项：--json（tools=布尔开关 / call=取下一个值）与 --timeout 秒数。 */
function parseInvokeFlags(rest, jsonTakesValue) {
  const opts = { positional: [] };
  for (let i = 0; i < rest.length; i++) {
    const a = rest[i];
    if (a === '--json') {
      if (jsonTakesValue) opts.argsJson = rest[++i];
      else opts.json = true;
    } else if (a === '--timeout') {
      const sec = Number(rest[++i]);
      if (!Number.isFinite(sec) || sec <= 0) throw Object.assign(new Error('--timeout expects seconds, e.g. --timeout 180'), { exitCode: 2 });
      opts.timeoutMs = sec * 1000;
    } else {
      opts.positional.push(a);
    }
  }
  return opts;
}

/**
 * CLI 入口分发：login / logout / status / --version / --help，
 * 无参数默认启动 stdio MCP 桥（Accio Work 以 `npx -y @geoly/accio-mcp` 起 MCP server 的约定）。
 */
async function main(argv) {
  const cmd = argv[0];

  if (cmd === '--version' || cmd === '-v') {
    console.log(VERSION);
    return;
  }
  if (cmd === '--help' || cmd === '-h' || cmd === 'help') {
    console.log(HELP);
    return;
  }
  // tools / call：agent 直调路径（Accio 官方包内 CLI 模式，同 dws——不经 MCP toolkit 注册）
  if (cmd === 'tools' || cmd === 'call') {
    try {
      const opts = parseInvokeFlags(argv.slice(1), cmd === 'call');
      if (cmd === 'tools') {
        await runTools(opts);
      } else {
        const name = opts.positional[0];
        if (!name) {
          console.error("[geoly] Usage: geoly-accio-mcp call <tool> --json '<args JSON>'");
          process.exit(2);
        }
        await runCall(name, opts.argsJson, opts);
      }
    } catch (e) {
      console.error(`[geoly] ${e.message}`);
      process.exit(e.exitCode ?? 1);
    }
    return;
  }
  if (cmd === 'login') {
    await login();
    return;
  }
  // 内部子命令（登录守护进程机制，勿在 help 暴露）：
  // __login_spawn__ = 双重派生中间层；__login_helper__ = 常驻回调/换 token/写凭据的守护进程
  if (cmd === '__login_spawn__') {
    runLoginSpawner();
    return;
  }
  if (cmd === '__login_helper__') {
    await runLoginHelper();
    return;
  }
  if (cmd === 'logout') {
    console.error(clearCredentials() ? '[geoly] Signed out.' : '[geoly] No stored session.');
    return;
  }
  if (cmd === 'status') {
    const creds = loadCredentials();
    console.log(
      creds
        ? `Signed in as ${creds.account}${creds.expires_at ? ` (token ${creds.expires_at > Date.now() ? 'valid' : 'expired'})` : ''}`
        : 'Not signed in.'
    );
    return;
  }
  if (cmd) {
    console.error(`[geoly] Unknown command: ${cmd}\n`);
    console.error(HELP);
    process.exit(2);
  }

  await runBridge();
}

// ==== cli entry ====

main(process.argv.slice(2)).catch((err) => {
  console.error(`[geoly] fatal: ${err?.message || err}`);
  process.exit(1);
});
