#!/usr/bin/env node
// AUTO-GENERATED by scripts/bundle-cli.mjs — do not edit. Source: packages/accio-mcp/

import { createHash, randomBytes } from 'node:crypto';
import { createServer } from 'node:http';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { spawn } from 'node:child_process';

// ==== config.mjs ====
/**
 * 全局常量配置。
 * GEOLY_BASE_URL 环境变量仅用于本地联调（指向 staging 等），生产默认 app.geoly.ai。
 * 凭据文件路径 ~/.geoly/credentials 是与 Accio Work connector 声明
 * （connectors.json → cli.credential.home = ".geoly/credentials"）绑定的硬契约，不能改。
 */
const BASE_URL = process.env.GEOLY_BASE_URL || 'https://app.geoly.ai';
const MCP_URL = `${BASE_URL}/api/mcp`;
const CRED_DIR = join(homedir(), '.geoly');
const CRED_FILE = join(CRED_DIR, 'credentials');
const CLIENT_NAME = 'geoly-accio-plugin';
const VERSION = "0.2.1";
const OAUTH_SCOPE = 'openid profile email offline_access';

// ==== credentials.mjs ====
/**
 * 读取本地凭据文件（~/.geoly/credentials）。
 * 文件不存在或解析失败一律返回 null，由调用方决定引导登录还是报错。
 */
function loadCredentials() {
  try {
    return JSON.parse(readFileSync(CRED_FILE, 'utf8'));
  } catch {
    return null;
  }
}

/**
 * 写入凭据文件。
 * Accio Work 的硬契约：顶层必须有明文 account / email 字段（框架用它渲染授权卡片的账号标签，
 * 只认顶层明文，不解嵌套、不解密），后续版本升级不得把这两个字段挪走或改名。
 */
function saveCredentials(creds) {
  mkdirSync(CRED_DIR, { recursive: true });
  writeFileSync(CRED_FILE, `${JSON.stringify(creds, null, 2)}\n`, { mode: 0o600 });
}

/** 删除凭据文件（logout 用）。 */
function clearCredentials() {
  try {
    rmSync(CRED_FILE);
    return true;
  } catch {
    return false;
  }
}

// ==== oauth.mjs ====
const LOGIN_TIMEOUT_MS = 10 * 60 * 1000;

/** base64url 编码（Node 18 Buffer 原生支持）。 */
function b64url(buf) {
  return Buffer.from(buf).toString('base64url');
}

/**
 * 拉取授权服务器元数据（RFC 8414）。
 * GEOly 生产返回 authorization/token/userinfo/registration 四个端点，均已实测存在。
 */
async function discoverAuthServer() {
  const res = await fetch(`${BASE_URL}/.well-known/oauth-authorization-server`, {
    headers: { Accept: 'application/json' },
  });
  if (!res.ok) throw new Error(`OAuth discovery failed: HTTP ${res.status}`);
  const meta = await res.json();
  for (const k of ['authorization_endpoint', 'token_endpoint', 'registration_endpoint']) {
    if (!meta[k]) throw new Error(`OAuth discovery missing ${k}`);
  }
  return meta;
}

/**
 * 动态客户端注册（RFC 7591）。
 * GEOly 支持 token_endpoint_auth_method=none 的公共客户端；redirect_uri 为本机 loopback 回调，
 * 每次登录端口随机，因此每次登录注册一个新 client（服务端幂等治理）。
 */
async function registerClient(meta, redirectUri) {
  const res = await fetch(meta.registration_endpoint, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
    body: JSON.stringify({
      client_name: 'GEOly Accio Plugin',
      redirect_uris: [redirectUri],
      grant_types: ['authorization_code', 'refresh_token'],
      response_types: ['code'],
      token_endpoint_auth_method: 'none',
      scope: OAUTH_SCOPE,
    }),
  });
  if (!res.ok) {
    throw new Error(`Dynamic client registration failed: HTTP ${res.status} ${await res.text()}`);
  }
  return res.json();
}

/**
 * 跨平台打开浏览器。用绝对路径调系统 opener（macOS 的 /usr/bin/open、Windows 的
 * cmd）——被 Accio 这类 GUI App 以受限 PATH 的子进程拉起时，相对命令名可能解析不到。
 * 失败不抛错：授权 URL 已经显著打印，用户可手动打开。返回是否成功派发。
 */
function openBrowser(url) {
  // ⚠️ Windows 不能裸走 `cmd /c start <url>`：URL 里的 & 是 cmd 元字符，会把 URL 在
  // 第一个 & 处截断（authorize 链接丢 client_id → invalid_client，实测复现）。
  // 首选 rundll32（不经 shell 解析，URL 原样传），cmd start 兜底时必须 ^ 转义 &。
  const candidates =
    process.platform === 'win32'
      ? [
          ['rundll32', ['url.dll,FileProtocolHandler', url]],
          ['cmd', ['/c', 'start', '', url.replace(/&/g, '^&')]],
        ]
      : process.platform === 'darwin'
        ? [['/usr/bin/open', [url]], ['open', [url]]]
        : [['/usr/bin/xdg-open', [url]], ['xdg-open', [url]]];
  for (const [cmd, args] of candidates) {
    try {
      const child = spawn(cmd, args, { stdio: 'ignore', detached: true });
      child.on('error', () => {});
      child.unref();
      return true;
    } catch {
      /* 试下一个候选 */
    }
  }
  return false;
}

/** 解 JWT payload（不验签——仅取展示用的 email/name；数据面鉴权在服务端）。 */
function decodeJwtPayload(jwt) {
  try {
    return JSON.parse(Buffer.from(jwt.split('.')[1], 'base64url').toString('utf8'));
  } catch {
    return null;
  }
}

/**
 * 授权码换 token（PKCE 公共客户端，带 RFC 8707 resource 参数指向 MCP 端点）。
 * refresh 时复用同一函数，grant 参数不同。
 */
async function tokenRequest(tokenEndpoint, params) {
  const res = await fetch(tokenEndpoint, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', Accept: 'application/json' },
    body: new URLSearchParams({ ...params, resource: MCP_URL }).toString(),
  });
  const body = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new Error(
      `Token request failed: HTTP ${res.status} ${body.error || ''} ${body.error_description || ''}`.trim()
    );
  }
  return body;
}

/**
 * 登录主流程：起 loopback 回调服务 → 发现端点 → DCR 注册 → 开浏览器授权(PKCE S256)
 * → 授权码换 token → 取用户身份(id_token 优先, userinfo 兜底) → 写 ~/.geoly/credentials。
 * 凭据文件顶层 account/email 明文是 Accio 授权卡片账号标签的硬契约。
 */
async function login() {
  const meta = await discoverAuthServer();

  const verifier = b64url(randomBytes(32));
  const challenge = b64url(createHash('sha256').update(verifier).digest());
  const state = b64url(randomBytes(16));

  // loopback 回调服务：端口随机，收到 /callback 即完成
  const { server, port, waitForCode } = await startCallbackServer(state);
  const redirectUri = `http://127.0.0.1:${port}/callback`;

  try {
    const client = await registerClient(meta, redirectUri);

    const authUrl = new URL(meta.authorization_endpoint);
    authUrl.search = new URLSearchParams({
      response_type: 'code',
      client_id: client.client_id,
      redirect_uri: redirectUri,
      scope: OAUTH_SCOPE,
      state,
      code_challenge: challenge,
      code_challenge_method: 'S256',
      resource: MCP_URL,
    }).toString();

    // 显著打印授权 URL 到 stdout 和 stderr：即便自动弹窗被 GUI 宿主的沙箱/PATH 拦掉，
    // Accio 或用户也能从日志里拿到链接手动打开。
    const banner = `\n========================================\nSign in to GEOly — open this URL in your browser:\n${authUrl}\n========================================\n`;
    process.stdout.write(banner);
    console.error(banner);
    const opened = openBrowser(authUrl.toString());
    console.error(
      opened
        ? '[geoly] Opened your default browser. Complete sign-in there.'
        : '[geoly] Could not auto-open a browser — please open the URL above manually.'
    );

    const code = await waitForCode;

    const tokens = await tokenRequest(meta.token_endpoint, {
      grant_type: 'authorization_code',
      code,
      redirect_uri: redirectUri,
      client_id: client.client_id,
      code_verifier: verifier,
    });

    // 身份信息：id_token 里拿 email/name；拿不到再打 userinfo；最后回退固定标签
    let identity = tokens.id_token ? decodeJwtPayload(tokens.id_token) : null;
    if (!identity?.email && meta.userinfo_endpoint) {
      identity = await fetch(meta.userinfo_endpoint, {
        headers: { Authorization: `Bearer ${tokens.access_token}` },
      })
        .then((r) => (r.ok ? r.json() : null))
        .catch(() => null);
    }
    const email = identity?.email || null;
    const account = email || identity?.name || 'GEOly account';

    saveCredentials({
      account,
      email,
      name: identity?.name || null,
      access_token: tokens.access_token,
      refresh_token: tokens.refresh_token || null,
      token_type: tokens.token_type || 'Bearer',
      expires_at: tokens.expires_in ? Date.now() + tokens.expires_in * 1000 : null,
      obtained_at: Date.now(),
      client_id: client.client_id,
      client_secret: client.client_secret || null,
      token_endpoint: meta.token_endpoint,
      base_url: BASE_URL,
      client: `${CLIENT_NAME}/${VERSION}`,
    });

    console.error(`[geoly] Signed in as ${account}. You can close the browser tab.`);
  } finally {
    server.close();
  }
}

/**
 * 起本机回调 HTTP 服务，返回 {server, port, waitForCode}。
 * 校验 state，向浏览器回一页成功/失败提示；超时 10 分钟自动失败退出。
 */
function startCallbackServer(expectedState) {
  let resolveCode;
  let rejectCode;
  const waitForCode = new Promise((resolve, reject) => {
    resolveCode = resolve;
    rejectCode = reject;
  });

  const timer = setTimeout(
    () => rejectCode(new Error('Sign-in timed out after 10 minutes')),
    LOGIN_TIMEOUT_MS
  );

  const server = createServer((req, res) => {
    const url = new URL(req.url, 'http://127.0.0.1');
    if (url.pathname !== '/callback') {
      res.writeHead(404).end();
      return;
    }
    const err = url.searchParams.get('error');
    const code = url.searchParams.get('code');
    const state = url.searchParams.get('state');
    const fail = err
      ? `Authorization failed: ${err} ${url.searchParams.get('error_description') || ''}`
      : state !== expectedState
        ? 'Authorization failed: state mismatch'
        : !code
          ? 'Authorization failed: missing code'
          : null;

    res.writeHead(fail ? 400 : 200, { 'Content-Type': 'text/html; charset=utf-8' });
    res.end(
      `<!doctype html><meta charset="utf-8"><title>GEOly</title><body style="font-family:system-ui;display:grid;place-items:center;height:90vh"><div style="text-align:center"><h2>${fail ? 'Sign-in failed' : 'Signed in to GEOly'}</h2><p>${fail ? fail : 'You can close this tab and return to Accio Work.'}</p></div>`
    );

    clearTimeout(timer);
    if (fail) rejectCode(new Error(fail));
    else resolveCode(code);
  });

  return new Promise((resolve, reject) => {
    server.on('error', reject);
    server.listen(0, '127.0.0.1', () => {
      resolve({ server, port: server.address().port, waitForCode });
    });
  });
}

/**
 * 用 refresh_token 刷新 access_token；服务端未轮换 refresh_token 时保留旧值。
 * 返回更新后的凭据对象（已落盘）。
 */
async function refreshCredentials(creds) {
  if (!creds?.refresh_token) throw new Error('no refresh_token');
  const params = {
    grant_type: 'refresh_token',
    refresh_token: creds.refresh_token,
    client_id: creds.client_id,
  };
  if (creds.client_secret) params.client_secret = creds.client_secret;
  const tokens = await tokenRequest(creds.token_endpoint, params);

  const next = {
    ...creds,
    access_token: tokens.access_token,
    refresh_token: tokens.refresh_token || creds.refresh_token,
    expires_at: tokens.expires_in ? Date.now() + tokens.expires_in * 1000 : creds.expires_at,
    obtained_at: Date.now(),
  };
  saveCredentials(next);
  return next;
}

// ==== bridge.mjs ====
const DEBUG = !!process.env.GEOLY_DEBUG;
const log = (...a) => DEBUG && console.error('[geoly-bridge]', ...a);

/** stdout 写一条 JSON-RPC 消息（newline-delimited，stdio MCP 传输格式）。 */
function writeMessage(msg) {
  process.stdout.write(`${JSON.stringify(msg)}\n`);
}

/** 给带 id 的请求回一条 JSON-RPC error（通知无 id 则静默丢弃）。 */
function writeError(id, code, message) {
  if (id === undefined || id === null) return;
  writeMessage({ jsonrpc: '2.0', id, error: { code, message } });
}

/**
 * token 管理器：GEOLY_API_KEY 环境变量（geom_ 静态只读 token）优先；
 * 否则用 ~/.geoly/credentials 的 OAuth token，过期前 60s 或收到 401 时用 refresh_token 换新。
 * refresh 单飞（并发请求共享同一次刷新）。
 */
function createTokenManager() {
  const staticKey = process.env.GEOLY_API_KEY || null;
  let creds = staticKey ? null : loadCredentials();
  let refreshing = null;

  const doRefresh = () => {
    refreshing ??= refreshCredentials(creds)
      .then((next) => {
        creds = next;
        return next;
      })
      .finally(() => {
        refreshing = null;
      });
    return refreshing;
  };

  return {
    /** 是否走 GEOLY_API_KEY 静态轨（影响 401 提示文案）。 */
    isStatic: !!staticKey,
    /** 取当前可用 token；无凭据返回 null。 */
    async get() {
      if (staticKey) return staticKey;
      if (!creds) {
        creds = loadCredentials();
        if (!creds) return null;
      }
      if (creds.expires_at && creds.expires_at - Date.now() < 60_000 && creds.refresh_token) {
        try {
          await doRefresh();
        } catch (e) {
          log('proactive refresh failed:', e.message);
        }
      }
      return creds.access_token || null;
    },
    /** 收到 401 后强制刷新一次；成功返回新 token，失败返回 null。 */
    async forceRefresh() {
      if (staticKey || !creds?.refresh_token) return null;
      try {
        await doRefresh();
        return creds.access_token || null;
      } catch (e) {
        log('refresh after 401 failed:', e.message);
        return null;
      }
    },
  };
}

/**
 * 解析 SSE 响应体（服务端对 POST 可能回 text/event-stream），
 * 把每个 event 的 data 行拼起来 JSON.parse 后逐条写回 stdout。
 */
async function pumpSseBody(res) {
  const decoder = new TextDecoder();
  let buf = '';
  const flushEvent = (raw) => {
    const data = raw
      .split('\n')
      .filter((l) => l.startsWith('data:'))
      .map((l) => l.slice(5).trimStart())
      .join('\n');
    if (!data) return;
    try {
      writeMessage(JSON.parse(data));
    } catch {
      log('unparseable SSE data:', data.slice(0, 200));
    }
  };
  for await (const chunk of res.body) {
    buf += decoder.decode(chunk, { stream: true });
    let idx;
    while ((idx = buf.indexOf('\n\n')) !== -1) {
      flushEvent(buf.slice(0, idx));
      buf = buf.slice(idx + 2);
    }
  }
  if (buf.trim()) flushEvent(buf);
}

/**
 * stdio ↔ Streamable HTTP 桥主循环。
 * GEOly 的远程 MCP 是无状态 Streamable HTTP（仅 POST；GET/DELETE 返 405、无服务端推送），
 * 因此桥是纯请求-响应转发：stdin 每行一条 JSON-RPC → POST 远端 → 响应(JSON 或 SSE)写回 stdout。
 */
async function runBridge() {
  const tokens = createTokenManager();
  let protocolVersion = null; // initialize 结果里记下，后续请求带 MCP-Protocol-Version 头

  const post = async (msg, token) => {
    const headers = {
      'Content-Type': 'application/json',
      Accept: 'application/json, text/event-stream',
      Authorization: `Bearer ${token}`,
      'X-Client-Name': CLIENT_NAME,
      'X-Client-Version': VERSION,
    };
    if (protocolVersion) headers['MCP-Protocol-Version'] = protocolVersion;
    return fetch(MCP_URL, { method: 'POST', headers, body: JSON.stringify(msg) });
  };

  const handle = async (msg) => {
    const id = msg?.id;
    let token = await tokens.get();
    if (!token) {
      writeError(
        id,
        -32002,
        'Not signed in to GEOly. Connect the GEOly connector (App Authorization → Connect), or run: npx -y @geoly/accio-mcp login'
      );
      return;
    }

    try {
      let res = await post(msg, token);

      // 401 → 强制 refresh 一次再重试；仍失败则提示重新授权
      if (res.status === 401) {
        token = await tokens.forceRefresh();
        if (token) res = await post(msg, token);
        if (!token || res.status === 401) {
          writeError(
            id,
            -32001,
            tokens.isStatic
              ? 'GEOLY_API_KEY was rejected (invalid or revoked geom_ token). Issue a new token in the GEOly dashboard.'
              : 'GEOly session expired. Reconnect the GEOly connector (App Authorization → Connect), or run: npx -y @geoly/accio-mcp login'
          );
          return;
        }
      }

      if (res.status === 202 || res.status === 204) return; // 通知已受理，无响应体

      const ctype = res.headers.get('content-type') || '';
      if (!res.ok) {
        const text = await res.text().catch(() => '');
        writeError(id, -32000, `GEOly MCP HTTP ${res.status}: ${text.slice(0, 400)}`);
        return;
      }

      if (ctype.includes('text/event-stream')) {
        await pumpSseBody(res);
        return;
      }

      const body = await res.json();
      for (const m of Array.isArray(body) ? body : [body]) {
        // 记录协商出的协议版本，供后续请求头使用
        if (m?.result?.protocolVersion) protocolVersion = m.result.protocolVersion;
        writeMessage(m);
      }
    } catch (e) {
      writeError(id, -32001, `GEOly MCP transport error: ${e.message}`);
    }
  };

  // stdin 逐行读取（newline-delimited JSON-RPC）。
  // 在途请求计数：stdin 关闭时必须等全部响应写完再退出，否则管道式客户端会丢响应。
  let pending = 0;
  let stdinEnded = false;
  const maybeExit = () => {
    if (stdinEnded && pending === 0) process.exit(0);
  };
  const track = (msg) => {
    pending++;
    void handle(msg).finally(() => {
      pending--;
      maybeExit();
    });
  };

  let buf = '';
  process.stdin.setEncoding('utf8');
  process.stdin.on('data', (chunk) => {
    buf += chunk;
    let idx;
    while ((idx = buf.indexOf('\n')) !== -1) {
      const line = buf.slice(0, idx).trim();
      buf = buf.slice(idx + 1);
      if (!line) continue;
      let msg;
      try {
        msg = JSON.parse(line);
      } catch {
        log('unparseable stdin line:', line.slice(0, 200));
        continue;
      }
      track(msg);
    }
  });
  process.stdin.on('end', () => {
    stdinEnded = true;
    maybeExit();
  });

  log(`bridge started → ${MCP_URL}`);
  // 保持进程存活直到 stdin 关闭
  await new Promise(() => {});
}

// ==== main.mjs ====
const HELP = `GEOly Accio connector CLI v${VERSION}

Usage:
  geoly-accio-mcp login     Sign in to GEOly in your browser (writes ~/.geoly/credentials)
  geoly-accio-mcp logout    Remove the stored GEOly session
  geoly-accio-mcp status    Show sign-in status
  geoly-accio-mcp           (no args) Run the stdio MCP bridge to ${MCP_URL}

Environment:
  GEOLY_API_KEY   Use a read-only geom_ static token instead of the stored login
  GEOLY_BASE_URL  Override the GEOly base URL (testing only)
  GEOLY_DEBUG     Verbose bridge logging on stderr
`;

/**
 * CLI 入口分发：login / logout / status / --version / --help，
 * 无参数默认启动 stdio MCP 桥（Accio Work 以 `npx -y @geoly/accio-mcp` 起 MCP server 的约定）。
 */
async function main(argv) {
  const cmd = argv[0];

  if (cmd === '--version' || cmd === '-v') {
    console.log(VERSION);
    return;
  }
  if (cmd === '--help' || cmd === '-h' || cmd === 'help') {
    console.log(HELP);
    return;
  }
  if (cmd === 'login') {
    await login();
    return;
  }
  if (cmd === 'logout') {
    console.error(clearCredentials() ? '[geoly] Signed out.' : '[geoly] No stored session.');
    return;
  }
  if (cmd === 'status') {
    const creds = loadCredentials();
    console.log(
      creds
        ? `Signed in as ${creds.account}${creds.expires_at ? ` (token ${creds.expires_at > Date.now() ? 'valid' : 'expired'})` : ''}`
        : 'Not signed in.'
    );
    return;
  }
  if (cmd) {
    console.error(`[geoly] Unknown command: ${cmd}\n`);
    console.error(HELP);
    process.exit(2);
  }

  await runBridge();
}

// ==== cli entry ====

main(process.argv.slice(2)).catch((err) => {
  console.error(`[geoly] fatal: ${err?.message || err}`);
  process.exit(1);
});
